"""base commit

Revision ID: cc049b46f4cf
Revises: 
Create Date: 2025-05-31 14:02:30.243314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc049b46f4cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
